---
deployment:
  tasks:
    # NOTE: public_html on cPanel must not be removed or renamed.
    # This folder has owner USER:nobody, and the USER user does not have
    # access to change owner. So this folder must stay as-is to keep the nobody
    # group, which is critical to the site working. A new folder won't work.
    - export DEPLOYPATH=/home/dimestor/public_html/bigraccoon.ca
    - export REPOPATH=/home/dimestor/repositories/bigraccoon-pico
    # Remove previous old files, if any.
#    - /bin/rm -Rf ${DEPLOYPATH}_old
    # Copy old site files to another directory.
#    - /bin/cp -R ${DEPLOYPATH} ${DEPLOYPATH}_old
    # Sync repository files to the deploy target path, excluding .git folder.
    # --delete-after will remove deleted files and folders after syncing.
    # Trailing slash on source means to copy the directory contents (and not the directory itself)
    - /bin/rsync -aP ${REPOPATH}/index.php ${DEPLOYPATH}/
    - /bin/rsync -aP ${REPOPATH}/config/ ${DEPLOYPATH}/config --delete-after
    - /bin/rsync -aP ${REPOPATH}/plugins/ ${DEPLOYPATH}/plugins --delete-after
    - /bin/rsync -aP ${REPOPATH}/themes/ ${DEPLOYPATH}/themes --delete-after
    - /bin/rsync -aP ${REPOPATH}/vendor/ ${DEPLOYPATH}/vendor --delete-after
 #   - /bin/rsync -aP --exclude '.git' --exclude '.well-known' ${REPOPATH}/ ${DEPLOYPATH} #--delete-after
    # Set correct permissions.
    - /bin/chmod 755 ${DEPLOYPATH}
    - /bin/find ${DEPLOYPATH} -type d -exec /bin/chmod 755 '{}' \;
    - /bin/find ${DEPLOYPATH} -type f -exec /bin/chmod 644 '{}' \;
